// Re-export from tmdb for convenience
export { getRatingColor, formatRuntime, getYear, GENRE_LIST, posterUrl, backdropUrl } from './tmdb'
export type { TMDBMovie as Movie } from './tmdb'

// Static featured movies for Hero section (TMDB IDs)
export const FEATURED_MOVIES = [
  {
    id: 693134,
    title: "Dune: Part Two",
    tagline: "Long live the fighters.",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    poster_path: "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    release_date: "2024-03-01",
    vote_average: 8.3,
    vote_count: 6842,
    genres: [{ id: 878, name: "Sci-Fi" }, { id: 12, name: "Adventure" }, { id: 18, name: "Drama" }],
    runtime: 166,
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Josh Brolin"],
    trailer_key: "Way9Dexny3w",
    status: "Released",
    original_language: "en",
    popularity: 312.4,
  },
  {
    id: 872585,
    title: "Oppenheimer",
    tagline: "The world forever changes.",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    poster_path: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    release_date: "2023-07-21",
    vote_average: 8.1,
    vote_count: 8931,
    genres: [{ id: 18, name: "Drama" }, { id: 36, name: "History" }, { id: 53, name: "Thriller" }],
    runtime: 180,
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    trailer_key: "uYPbbksJxIg",
    status: "Released",
    original_language: "en",
    popularity: 289.1,
  },
  {
    id: 792307,
    title: "Poor Things",
    tagline: "An adventure of sex, self-discovery and sheer delight.",
    overview: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    poster_path: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXIRspEnYpMpKs.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
    release_date: "2023-12-08",
    vote_average: 8.0,
    vote_count: 5124,
    genres: [{ id: 35, name: "Comedy" }, { id: 18, name: "Drama" }, { id: 878, name: "Sci-Fi" }],
    runtime: 141,
    director: "Yorgos Lanthimos",
    cast: ["Emma Stone", "Mark Ruffalo", "Willem Dafoe", "Ramy Youssef"],
    trailer_key: "RlbR5N6veqw",
    status: "Released",
    original_language: "en",
    popularity: 198.7,
  },
  {
    id: 940721,
    title: "Godzilla Minus One",
    tagline: "Japan is already in ruins.",
    overview: "In postwar Japan, Godzilla brings new devastation to an already struggling nation attempting to recover.",
    poster_path: "https://image.tmdb.org/t/p/w500/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
    release_date: "2023-12-01",
    vote_average: 7.9,
    vote_count: 3521,
    genres: [{ id: 28, name: "Action" }, { id: 878, name: "Sci-Fi" }, { id: 18, name: "Drama" }],
    runtime: 125,
    director: "Takashi Yamazaki",
    cast: ["Ryunosuke Kamiki", "Minami Hamabe"],
    status: "Released",
    original_language: "ja",
    popularity: 210.2,
  },
  {
    id: 787699,
    title: "Wonka",
    tagline: "Every good thing in this world started with a dream.",
    overview: "The story of how the world's greatest inventor, magician and chocolate-maker became the beloved Willy Wonka we know today.",
    poster_path: "https://image.tmdb.org/t/p/w500/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/original/yyRLze7KpqKYdGD6ahsbMWpYEKA.jpg",
    release_date: "2023-12-15",
    vote_average: 7.1,
    vote_count: 5210,
    genres: [{ id: 35, name: "Comedy" }, { id: 14, name: "Fantasy" }, { id: 10751, name: "Family" }],
    runtime: 116,
    director: "Paul King",
    cast: ["Timothée Chalamet", "Calah Lane", "Hugh Grant"],
    status: "Released",
    original_language: "en",
    popularity: 245.1,
  },
]

export const TRENDING_MOVIES = FEATURED_MOVIES.slice(0, 5)
